import = ["/home/ivche/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "SourceCodeVF"

[window]
opacity = 0.7

# [window.padding]
# x = 10
# y = 10
